TARGET = XK-1
APP_NAME =
XCC_FLAGS = -O3 -g -D ADAT_REF=100
USED_MODULES = module_adat_rx

#=============================================================================
# The following part of the Makefile includes the common build infrastructure
# for compiling XMOS applications. You should not need to edit below here.


# Use the main Makefile from module_xmos_common
include ../../xcommon/module_xcommon/build/Makefile.common
